FROM python:3.10 AS base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG PER_CONF_DIR
ARG SECRET_KEY
ARG URL_PREFIX
ARG BUBLIK_UI_DIR
ARG BUBLIK_SRC
ARG TE_BASE
ARG TMPDIR
ARG BUBLIK_LOGDIR
ARG BUBLIK_LOG
ARG BUBLIK_ACCESS_LOG
ARG MANAGEMENT_COMMANDS_LOG
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_PORT
ARG CELERY_APP
ARG CELERY_BROKER_URL
ARG CELERY_RESULT_BACKEND
ARG CELERY_ACCEPT_CONTENT
ARG CELERY_TASK_SERIALIZER
ARG CELERY_RESULT_SERIALIZER
ARG CELERY_CREATE_DIRS
ARG CELERYD_MAX_TASKS_PER_CHILD
ARG CELERY_LOG_LEVEL
ARG FLOWER_PERSISTENT
ARG FLOWER_PORT
ARG FLOWER_URL_PREFIX
ARG REDIS_HOST
ARG BUBLIK_BIND_GUNICORN
ARG BUBLIK_WORKERS
ARG BUBLIK_TIMEOUT
ARG BUBLIK_GRACEFUL_TIMEOUT
ARG BUBLIK_WEB_NAME

ENV PER_CONF_DIR=${PER_CONF_DIR}
ENV SECRET_KEY=${SECRET_KEY}
ENV URL_PREFIX=${URL_PREFIX}
ENV BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
ENV BUBLIK_SRC=${BUBLIK_SRC}
ENV TE_BASE=${TE_BASE}
ENV TMPDIR=${TMPDIR}
ENV BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
ENV BUBLIK_LOG=${BUBLIK_LOG}
ENV BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
ENV MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV CELERY_APP=${CELERY_APP}
ENV CELERY_BROKER_URL=${CELERY_BROKER_URL}
ENV CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
ENV CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
ENV CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
ENV CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
ENV CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
ENV CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
ENV CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
ENV FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
ENV FLOWER_PORT=${FLOWER_PORT}
ENV FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
ENV REDIS_HOST=${REDIS_HOST}
ENV BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
ENV BUBLIK_WORKERS=${BUBLIK_WORKERS}
ENV BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
ENV BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
ENV BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}

ENV PATH="/app/te/build/inst/default/bin:$PATH"

WORKDIR /app

RUN apt update \
  && apt install \
  gettext \
  python3-celery \
  rsync \
  flex \
  bison \
  ninja-build \
  libjansson-dev \
  libjansson-doc \
  libjansson4 \
  libpopt-dev \
  libpcre3-dev \
  pixz \
  libxml-parser-perl \
  build-essential -y && \
  cpan JSON

RUN pip install --upgrade pip && pip install meson watchfiles

RUN mkdir bublik

COPY ./requirements.txt bublik

RUN pip install -r /app/bublik/requirements.txt

WORKDIR /app/te

COPY ./test-environment .
RUN ./dispatcher.sh -q --conf-builder=builder.conf.tools --no-run

# 2. Build bublik
FROM base AS runner

WORKDIR /app

COPY . ./bublik
COPY ./bublik-conf ./bublik

# 3. Create user and set permissions
RUN mkdir -p bublik/logs
RUN chmod +x ./bublik/entrypoint.sh

WORKDIR /app/bublik
