# Generated by Django 5.1.7 on 2025-06-29 17:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_project_field(apps, schema_editor):
    Meta = apps.get_model('data', 'Meta')
    MetaCategory = apps.get_model('data', 'MetaCategory')
    if not MetaCategory.objects.exists():
        return
    current_project = Meta.objects.filter(type='label', name='PROJECT').first()
    if current_project:
        MetaCategory.objects.filter(project__isnull=True).update(project=current_project)


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_metatest_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="metacategory",
            name="project",
            field=models.ForeignKey(
                null=True,
                limit_choices_to={"name": "PROJECT", "type": "label"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_metacategories",
                to="data.meta",
            ),
        ),
        migrations.RunPython(backfill_project_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="metacategory",
            name="name",
            field=models.CharField(help_text="Name of the category.", max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="metacategory",
            unique_together={("name", "project")},
        ),
    ]
